### ISSUE TITLE
关于城市名称提取的想法

### ISSUE THREAD

**Issue by 4timespassedCET4** [Ctipsy/DA_projects#1]
这几天都在看作者的这个项目，让我学到了很多，谢谢！
我有一点想法关于visualization_analysis.py中的count_city这部分，我觉得可以使用jieba.cut（）分词，设置参数cut_all = Fasle来分割城市，因为jieba分词在这方面还是非常准确地，我查看了分词后的结果，如下：

![1](https://user-images.githubusercontent.com/39053129/43265124-7abf1d22-911a-11e8-9194-b439e4b9b4af.png)

 

，有一个需要优化的地方：比如辽宁沈阳，福建厦门，有时候没有分开，我们可以通过re.sub（）把省份替换为‘’（空），就只剩城市了，最后我们直接比对剩下的城市在不在pyecharts城市列表中就可以了，因为省份被jieba直接分开了，所以也就不用判断其他的了，这是最后的结果

![2](https://user-images.githubusercontent.com/39053129/43265214-b5c1e27e-911a-11e8-8d61-cbc2c2589c55.png)
代码写得比较丑就没放上来了，只是一种思路

**Comment by Ctipsy** [comment]
Nice Idea，可以Pull request一下吗o(∩_∩)o

**Comment by Ctipsy** [comment]
已经merge了，thx for your idea
